### pytorch 安装配置
查看cuda版本，cmd，nvidia-smi 则显示：如下示例：CUDA Version: 11.2

In [48]:
import torch
a=torch.tensor([1,3,5,600,5,3.0])
b=torch.tensor([2,5,3,8,7,6.0])
data=torch.stack([a,b],dim=1)              
norm_data=torch.nn.functional.normalize(data,dim=0)  #按列进行标准化
print(data)
print(norm_data)

tensor([[  1.,   2.],
        [  3.,   5.],
        [  5.,   3.],
        [600.,   8.],
        [  5.,   7.],
        [  3.,   6.]])
tensor([[0.0017, 0.1463],
        [0.0050, 0.3656],
        [0.0083, 0.2194],
        [0.9999, 0.5850],
        [0.0083, 0.5119],
        [0.0050, 0.4388]])


In [75]:
import numpy as np 
import pandas as pd
#data=np.random.randn(5000,10)
#data=pd.DataFrame(data)
#data.to_csv(os.path.join(os.getcwd(),'data\\test_data.csv'))
file_path=os.path.join(os.getcwd(),'data\\test_data.csv')
data=pd.read_csv(file_path)
tensor=torch.Tensor(data.values)
length=len(tensor)
labels=torch.Tensor(list(range(length)))
labels=labels.unsqueeze(1)
torch_cat=torch.cat((tensor,labels),1)
train_tensor,test_tensor=torch.utils.data.random_split(tensor,[4000,1000])
train=torch.utils.data.DataLoader(train_tensor,batch_size=2,shuffle=True)   #从tensor矩阵中随机提取数据
next(iter(train))

tensor([[ 2.9730e+03, -6.9710e-01, -2.5537e-01,  1.8391e-01,  4.3145e-01,
         -8.5754e-01, -4.4181e-01, -6.1396e-01,  1.1652e+00,  1.1576e-01,
         -1.5643e+00],
        [ 4.3340e+03,  5.2740e-01, -2.1541e+00, -4.8767e-01, -2.2971e-01,
         -1.9468e+00, -1.3086e+00, -1.4069e+00, -8.5967e-01,  3.6927e-01,
          1.2411e+00]])

In [96]:
'''
自定义dataset类，提取dataframe中的数据，__init__,__len__,__getitem__三个函数必须有
可参考pytorch官方文档，自定义dataset
'''
import os
import pandas as pd
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, dataset_path,labels):
        self.data_set = pd.read_csv(dataset_path)
        self.labels=labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        data=self.data_set
        data=torch.Tensor(data.values)
        data=data[idx]
        label =self.labels[idx]
        return data, label
labels=torch.Tensor(list(range(length)))
dt=CustomDataset(file_path,labels)    #实例化CustomDataset类，类的实例化传入初始函数中的参数
train=torch.utils.data.DataLoader(dt,batch_size=2,shuffle=True)   #直接将类的实例化对象传入即可
data_set,label=next(iter(train))