In [4]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt


import os
import pandas as pd
from torchvision.io import read_image

class CustomImageDataset(Dataset):
    def __init__(self, annotations_file, img_dir, transform=None, target_transform=None):
        self.img_labels = pd.read_csv(annotations_file)
        self.img_dir = img_dir
        self.transform = transform   #modify the features
        self.target_transform = target_transform #modify the labels

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label

### The labels.csv file looks like:

tshirt1.jpg, 0

tshirt2.jpg, 0

......

ankleboot999.jpg, 9

In [2]:
# DataLoader is an iterable that abstracts this complexity for us in an easy API.
from torch.utils.data import DataLoader
train_dataloader = DataLoader(training_data, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=64, shuffle=True)

# Display image and label.
train_features, train_labels = next(iter(train_dataloader))
print(f"Feature batch shape: {train_features.size()}")
print(f"Labels batch shape: {train_labels.size()}")
img = train_features[0].squeeze()
label = train_labels[0]
plt.imshow(img, cmap="gray")
plt.show()
print(f"Label: {label}")

NameError: name 'training_data' is not defined

In [32]:
import torch
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda

ds = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
     #生成ont-hote-code,如果标签属于第三个类别，则在列表第三个位置生成为1，其他位置为0
    target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1)) 
)
f=lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1)
f(5)

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [13]:
torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(9),value=1)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [25]:
f=lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1)

In [31]:
f([6])

tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [3]:
import torch

In [5]:
torch.Tensor.r(3,10,10)

TypeError: descriptor 'random_' for 'torch._C._TensorBase' objects doesn't apply to a 'int' object