In [2]:
import os
import tensorflow as tf
import cProfile

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [3]:
tf.executing_eagerly()

True

In [73]:
d=tf.constant([[[ 0 , 1 , 2 ,3,  4],
            [ 5 , 6 , 7 , 8,  9]],
           [[10 ,11 ,12 ,13 ,14],
            [15 ,16 ,17 ,18 ,19]],
           [[20 ,21 ,22 ,23 ,24],
            [25 ,26 ,27 ,28 ,299999999]]])


In [64]:
tf.reshape(d,[5,6],'\n')

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])>

In [74]:
tf.cast(d,dtype=tf.uint8)

<tf.Tensor: shape=(3, 2, 5), dtype=uint8, numpy=
array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]],

       [[ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19]],

       [[ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28, 255]]], dtype=uint8)>

In [80]:
tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [83]:
tf.debugging.set_log_device_placement(True)

In [172]:
w = tf.Variable([[2.0, 3.0], [3.0, 4.0]],name='w')
b=tf.Variable([0.,0.],name='b')
x=[[1.0,2.0]]
with tf.GradientTape(persistent=True) as tape:
    y = x @ w + b
    loss = tf.reduce_mean(y**2)  #tf.reduce_mean计算x@w两个矩阵乘积平方的平均值，即loss=92.5

In [173]:
my_vars = {
    'w': w,
    'b': b
}
grad = tape.gradient(loss, my_vars) #计算矩阵w*x+b=loss值得对应关系系数，即梯度
grad

{'w': <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 8., 11.],
        [16., 22.]], dtype=float32)>,
 'b': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 8., 11.], dtype=float32)>}

 x @ w 

In [3]:
import numpy as np 
d=np.arange(0,15)
d=d.reshape(3,5)
d=tf.convert_to_tensor(d)#把numpy转化为tf张量类型

In [4]:
d

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])>

In [10]:
tf.slice(d,[0,2],[3,3]) #[2,2]代表扩展几行几列

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])>

In [235]:
d

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])>

In [16]:
%%time
tf.gather(d, [[0,1,2], [0,3,2],[0,1,2]],axis=1, batch_dims=1)

Wall time: 1 ms


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 5,  8,  7],
       [10, 11, 12]])>