# 卷积计算

In [84]:
import numpy as np
import cv2 as cv
a=np.array([[2,4,5,3],[1,1,7,1],[2,4,7,2]],np.uint8)
kernel=np.ones((3,3))/9
print(a)
print(kernel)

[[2 4 5 3]
 [1 1 7 1]
 [2 4 7 2]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [85]:
cv.filter2D(a,-1,kernel)#边界用与边界相邻的第二列、行进行补充,然后从左上角第一个像素遍历计算

array([[2, 3, 3, 5],
       [3, 4, 4, 5],
       [2, 3, 3, 5]], dtype=uint8)

In [92]:
b=np.array([[1,1,1],[4,2,4],[1,1,1]],np.uint8)

In [93]:
cv.filter2D(b,cv.,kernel)

array([[2, 3, 2],
       [2, 2, 2],
       [2, 3, 2]], dtype=uint8)

In [94]:
np.sum(b)*0.11111

1.77776

In [98]:
a=np.array([1,6,3],np.uint8)
b=cv.pyrDown(a,b)   #pyrdwon 先进行高斯平滑，然后隔1采1
print(a)
print(b)

[1 6 3]
[[4]
 [4]]


In [7]:
from google.colab import files

ModuleNotFoundError: No module named 'google'